#!/usr/bin/env ruby

require 'activejob-google_cloud_pubsub'
require 'google/cloud/pubsub'
require 'optparse/kwargs'

Version = ActiveJob::GoogleCloudPubsub::VERSION

args = {
  require: './config/environment'
}

opt = OptionParser.new

opt.on '--[no-]require=PATH' do |v|
  args[:require] = v
end

worker_args = opt.define_by_keywords(
  {},
  ActiveJob::GoogleCloudPubsub::Worker.instance_method(:initialize),
  {
    min_threads: Integer,
    max_threads: Integer
  }
)

pubsub_args = opt.define_by_keywords(
  {},
  Google::Cloud::Pubsub.method(:new),
  {
    scope:   Array,
    timeout: Integer
  }
)

opt.parse ARGV

require args[:require] if args[:require]

ActiveJob::GoogleCloudPubsub::Worker.new(**worker_args, **pubsub_args).run
