#!/usr/bin/env ruby

require 'activejob-google_cloud_pubsub'
require 'google/cloud/pubsub'
require 'optparse/kwargs'

Version = ActiveJob::GoogleCloudPubsub::VERSION

opts = {
  require: './config/environment'
}

parser = OptionParser.new

parser.on '--[no-]require=PATH' do |v|
  opts[:require] = v
end

worker_opts = parser.define_by_keywords(
  {},
  ActiveJob::GoogleCloudPubsub::Worker.instance_method(:initialize),
  {
    min_threads: Integer,
    max_threads: Integer
  }
)

pubsub_opts = parser.define_by_keywords(
  {},
  Google::Cloud::Pubsub.method(:new),
  {
    scope:   Array,
    timeout: Integer
  }
)

parser.parse ARGV

require opts[:require] if opts[:require]

ActiveJob::GoogleCloudPubsub::Worker.new(**worker_opts, **pubsub_opts).run
